### ISSUE TITLE
about square layer

### ISSUE THREAD

**Issue by magicffourier** [layumi/Person-reID-verification#3]
Hi, as you mentioned.
>  I use x*y instead of (x-y)^2 as Square Layer. (We do not need to worry about the scale of x and y.)
I am not sure what you meant by "(We do not need to worry about the scale of x and y.)" ,for x*y in PyTorch require the same shape.
could you please explain about this?

**Comment by Deeplearning20** [comment]
@layumi  I also don't understand "(We do not need to worry about the scale of x and y)". Can you explain more about it? Thanks

**Comment by layumi** [comment]
@magicffourier @Deeplearning20 

If the value of x or y is too large, it may case the large loss. 
(x-y)^2 = x^2 + y^2 -2*x*y.

In this code, I normalized the x and y.  https://github.com/layumi/Person-reID-verification/blob/master/model.py#L50-L52
So (x-y) ^2 = 2 - 2*x*y.

Since we use this feature to do verification, the constant 2 could be skipped as well.
I directly use the cosine distance x*y.

**Comment by Deeplearning20** [comment]
Thanks very much!

**Comment by magicffourier** [comment]
Thanks a lot!
